# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'message_label.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_message(object):
    def setupUi(self, widget_message):
        widget_message.setObjectName("widget_message")
        widget_message.resize(448, 55)
        widget_message.setStyleSheet("")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(widget_message)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spacer_left = QtWidgets.QLabel(widget_message)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spacer_left.sizePolicy().hasHeightForWidth())
        self.spacer_left.setSizePolicy(sizePolicy)
        self.spacer_left.setText("")
        self.spacer_left.setObjectName("spacer_left")
        self.horizontalLayout_2.addWidget(self.spacer_left)
        self.background_widget = QtWidgets.QWidget(widget_message)
        self.background_widget.setObjectName("background_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.background_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_from_time = QtWidgets.QLabel(self.background_widget)
        self.label_from_time.setText("")
        self.label_from_time.setObjectName("label_from_time")
        self.horizontalLayout.addWidget(self.label_from_time)
        self.label_nickname = QtWidgets.QLabel(self.background_widget)
        self.label_nickname.setObjectName("label_nickname")
        self.horizontalLayout.addWidget(self.label_nickname)
        self.label_message = QtWidgets.QLabel(self.background_widget)
        self.label_message.setWordWrap(False)
        self.label_message.setObjectName("label_message")
        self.horizontalLayout.addWidget(self.label_message)
        self.horizontalLayout_2.addWidget(self.background_widget)
        self.spacer_right = QtWidgets.QLabel(widget_message)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spacer_right.sizePolicy().hasHeightForWidth())
        self.spacer_right.setSizePolicy(sizePolicy)
        self.spacer_right.setText("")
        self.spacer_right.setObjectName("spacer_right")
        self.horizontalLayout_2.addWidget(self.spacer_right)

        self.retranslateUi(widget_message)
        QtCore.QMetaObject.connectSlotsByName(widget_message)

    def retranslateUi(self, widget_message):
        _translate = QtCore.QCoreApplication.translate
        widget_message.setWindowTitle(_translate("widget_message", "Form"))
        self.label_nickname.setText(_translate("widget_message", "nickname"))
        self.label_message.setText(_translate("widget_message", "txt_message"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_message = QtWidgets.QWidget()
    ui = Ui_widget_message()
    ui.setupUi(widget_message)
    widget_message.show()
    sys.exit(app.exec_())
