# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_chat_room.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_talk_room_widget(object):
    def setupUi(self, talk_room_widget):
        talk_room_widget.setObjectName("talk_room_widget")
        talk_room_widget.resize(600, 850)
        talk_room_widget.setStyleSheet("#talk_room_widget {\n"
"    background-color: #25316D;\n"
"    color: #1D5D9B;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"    color: #1D5D9B;\n"
"    font: bold 16pt \"나눔고딕\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:#F4D160;\n"
"    color: #1D5D9B;\n"
"    font: bold 12pt \"나눔고딕\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#FFFF9D;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:#FEF5AC;\n"
"}\n"
"\n"
"#header_frame QPushButton\n"
"{\n"
"    background-color:#1D5D9B;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"#header_frame QPushButton:hover\n"
"{\n"
"    background-color:#B0DAFF;\n"
"}\n"
"\n"
"#header_frame QPushButton:pressed\n"
"{\n"
"    background-color:#9AC5F4;\n"
"}\n"
"\n"
"#widget_title_wrapper{\n"
"    background-color:#F8FDCF;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"\n"
"#widget_title_wrapper #label_member_count{\n"
"    color: #453C67;\n"
"}\n"
"#header_frame #label_member_count:hover{\n"
"    color: #FBEEAC\n"
"}\n"
"\n"
"\n"
"#label_title{\n"
"    font: bold 20pt \"나눔고딕\";\n"
"    color: #7286D3;\n"
"}\n"
"#label_member_count{\n"
"    font: bold 15pt \"나눔고딕\";\n"
"    color: #F4D160;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    color: #1D5D9B;\n"
"    font: bold 12pt \"나눔고딕\";\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(talk_room_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(talk_room_widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.header_frame = QtWidgets.QFrame(self.frame_3)
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_title_wrapper = QtWidgets.QWidget(self.header_frame)
        self.widget_title_wrapper.setMinimumSize(QtCore.QSize(250, 0))
        self.widget_title_wrapper.setObjectName("widget_title_wrapper")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_title_wrapper)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_title = QtWidgets.QLabel(self.widget_title_wrapper)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_3.addWidget(self.label_title)
        self.horizontalLayout_2.addWidget(self.widget_title_wrapper)
        self.widget_member_count = QtWidgets.QWidget(self.header_frame)
        self.widget_member_count.setObjectName("widget_member_count")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_member_count)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_member_icon = QtWidgets.QLabel(self.widget_member_count)
        self.label_member_icon.setText("")
        self.label_member_icon.setPixmap(QtGui.QPixmap(":/newPrefix/user.svg"))
        self.label_member_icon.setObjectName("label_member_icon")
        self.horizontalLayout.addWidget(self.label_member_icon)
        self.label_member_count = QtWidgets.QLabel(self.widget_member_count)
        self.label_member_count.setObjectName("label_member_count")
        self.horizontalLayout.addWidget(self.label_member_count)
        self.horizontalLayout_2.addWidget(self.widget_member_count)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_member_plus = QtWidgets.QPushButton(self.header_frame)
        self.btn_member_plus.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_member_plus.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_member_plus.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/user-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_member_plus.setIcon(icon)
        self.btn_member_plus.setIconSize(QtCore.QSize(40, 40))
        self.btn_member_plus.setObjectName("btn_member_plus")
        self.horizontalLayout_2.addWidget(self.btn_member_plus)
        self.btn_member_minus = QtWidgets.QPushButton(self.header_frame)
        self.btn_member_minus.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_member_minus.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_member_minus.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_member_minus.setIcon(icon1)
        self.btn_member_minus.setIconSize(QtCore.QSize(40, 40))
        self.btn_member_minus.setObjectName("btn_member_minus")
        self.horizontalLayout_2.addWidget(self.btn_member_minus)
        self.btn_flist_close = QtWidgets.QPushButton(self.header_frame)
        self.btn_flist_close.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_flist_close.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_flist_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/x-yellow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_flist_close.setIcon(icon2)
        self.btn_flist_close.setIconSize(QtCore.QSize(40, 40))
        self.btn_flist_close.setObjectName("btn_flist_close")
        self.horizontalLayout_2.addWidget(self.btn_flist_close)
        self.verticalLayout_3.addWidget(self.header_frame)
        self.frame_11 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_11)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.chatting_area = QtWidgets.QWidget()
        self.chatting_area.setGeometry(QtCore.QRect(0, 0, 576, 684))
        self.chatting_area.setObjectName("chatting_area")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.chatting_area)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.chatting_area)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.chatting_area)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 640, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.scrollArea.setWidget(self.chatting_area)
        self.horizontalLayout_9.addWidget(self.scrollArea)
        self.verticalLayout_3.addWidget(self.frame_11)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_transfer_file = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_transfer_file.sizePolicy().hasHeightForWidth())
        self.btn_transfer_file.setSizePolicy(sizePolicy)
        self.btn_transfer_file.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_transfer_file.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btn_transfer_file.setObjectName("btn_transfer_file")
        self.horizontalLayout_10.addWidget(self.btn_transfer_file)
        self.user_chatting_lineedit = QtWidgets.QLineEdit(self.frame_9)
        self.user_chatting_lineedit.setMinimumSize(QtCore.QSize(0, 30))
        self.user_chatting_lineedit.setClearButtonEnabled(False)
        self.user_chatting_lineedit.setObjectName("user_chatting_lineedit")
        self.horizontalLayout_10.addWidget(self.user_chatting_lineedit)
        self.btn_chat_enter = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_chat_enter.sizePolicy().hasHeightForWidth())
        self.btn_chat_enter.setSizePolicy(sizePolicy)
        self.btn_chat_enter.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_chat_enter.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btn_chat_enter.setObjectName("btn_chat_enter")
        self.horizontalLayout_10.addWidget(self.btn_chat_enter)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(talk_room_widget)
        QtCore.QMetaObject.connectSlotsByName(talk_room_widget)

    def retranslateUi(self, talk_room_widget):
        _translate = QtCore.QCoreApplication.translate
        talk_room_widget.setWindowTitle(_translate("talk_room_widget", "Form"))
        self.label_title.setText(_translate("talk_room_widget", "테스트 1번방"))
        self.label_member_count.setText(_translate("talk_room_widget", "2"))
        self.btn_transfer_file.setText(_translate("talk_room_widget", "파일 첨부"))
        self.btn_chat_enter.setText(_translate("talk_room_widget", "입력"))
from code.front.ui import my_qrc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    talk_room_widget = QtWidgets.QWidget()
    ui = Ui_talk_room_widget()
    ui.setupUi(talk_room_widget)
    talk_room_widget.show()
    sys.exit(app.exec_())
