# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_custom_message_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_custom_message_box(object):
    def setupUi(self, custom_message_box):
        custom_message_box.setObjectName("custom_message_box")
        custom_message_box.resize(366, 171)
        custom_message_box.setStyleSheet("#custom_message_box{\n"
"    background-color: #1D5D9B;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #F4D160;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: #FBEEAC;\n"
"    font: bold 16pt \"나눔고딕\";\n"
"}\n"
"\n"
"#label_contents{\n"
"    font: bold 12pt;\n"
"    color : #1D5D9B;\n"
"}\n"
"#widget_outer{\n"
"    background-color:#75C2F6;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:#F4D160;\n"
"    color: #1D5D9B;\n"
"    font: bold 12pt \"나눔고딕\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#FFFF9D;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:#FEF5AC;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(custom_message_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_outer = QtWidgets.QWidget(custom_message_box)
        self.widget_outer.setObjectName("widget_outer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_outer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.widget_outer)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_title = QtWidgets.QLabel(self.widget)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_3.addWidget(self.label_title)
        self.label_contents = QtWidgets.QLabel(self.widget)
        self.label_contents.setObjectName("label_contents")
        self.verticalLayout_3.addWidget(self.label_contents)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.widget_outer)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(147, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_yes = QtWidgets.QPushButton(self.widget_2)
        self.btn_yes.setObjectName("btn_yes")
        self.horizontalLayout.addWidget(self.btn_yes)
        self.btn_no = QtWidgets.QPushButton(self.widget_2)
        self.btn_no.setObjectName("btn_no")
        self.horizontalLayout.addWidget(self.btn_no)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget_outer)

        self.retranslateUi(custom_message_box)
        QtCore.QMetaObject.connectSlotsByName(custom_message_box)

    def retranslateUi(self, custom_message_box):
        _translate = QtCore.QCoreApplication.translate
        custom_message_box.setWindowTitle(_translate("custom_message_box", "Form"))
        self.label_title.setText(_translate("custom_message_box", "TextLabel"))
        self.label_contents.setText(_translate("custom_message_box", "TextLabel"))
        self.btn_yes.setText(_translate("custom_message_box", "확인"))
        self.btn_no.setText(_translate("custom_message_box", "취소"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    custom_message_box = QtWidgets.QWidget()
    ui = Ui_custom_message_box()
    ui.setupUi(custom_message_box)
    custom_message_box.show()
    sys.exit(app.exec_())
